"""empty message

Revision ID: 03be42056150
Revises: 71f6043aa42c
Create Date: 2020-11-26 15:29:01.924240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03be42056150'
down_revision = '71f6043aa42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
