"""empty message

Revision ID: 398886dcbee4
Revises: d13056775f0a
Create Date: 2020-11-27 12:35:02.703434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398886dcbee4'
down_revision = 'd13056775f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
