"""empty message

Revision ID: 59d25b217780
Revises: ea1a9ff2273b
Create Date: 2020-11-27 12:39:36.163647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d25b217780'
down_revision = 'ea1a9ff2273b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
