"""empty message

Revision ID: 6933c20c0b59
Revises: 47865a3e0a30
Create Date: 2020-11-30 12:59:44.791205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6933c20c0b59'
down_revision = '47865a3e0a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
