"""empty message

Revision ID: ea1a9ff2273b
Revises: 398886dcbee4
Create Date: 2020-11-27 12:37:10.567119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1a9ff2273b'
down_revision = '398886dcbee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
