"""empty message

Revision ID: f514218a6f66
Revises: f90ab401bf81
Create Date: 2020-11-30 13:07:23.669680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f514218a6f66'
down_revision = 'f90ab401bf81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.drop_column('users', 'isAdmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
