"""empty message

Revision ID: f90ab401bf81
Revises: 6933c20c0b59
Create Date: 2020-11-30 13:04:10.956931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90ab401bf81'
down_revision = '6933c20c0b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isAdmin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'isAdmin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
